### ISSUE TITLE
Codebook Loading Icon Issue

### ISSUE THREAD

**Issue by mhickle** [RhoInc/CAT#34]
Two CSS files were loaded at the same time causing the Codebook loadinf icon styling to change.

To Recreate Bug:
Load and render v1.3.1-dev Codebook   - normal loading icon will show
Load and render v1.3.0-dev Codebook   - older normal loading icon will show
Switch back to  v1.3.1-dev Codebook     - huge abnormal loading icon will show

**Comment by jwildfire** [comment]
Resolved in newer versions of codebook.
