### ISSUE TITLE
Add a /?draw option

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/CAT#85]
Chart will draw when page is loaded if ?draw is included in URL. 

Just the parameter is needed - values are fine, but are ignored. That is `?draw`, `?draw=true`, `?draw=false`, `?draw=Picasso` are all fine and have the same result.

**Comment by samussiah** [comment]
Why wouldn't you want the chart to draw?

**Comment by jwildfire** [comment]
@samussiah Right now the default behavior is to wait until the user clicks render. Saves us from loading unneeded libraries if user is going to tweak stuff. Once we deal more rigorously with onDestroy cleanup, I think it makes sense to draw by default, but for now, going to leave default as false.

**Comment by samussiah** [comment]
closed in #86
